config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#main'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/about', to: 'users#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # get '/user/home', to: 'users#home', as: 'homepage'
  #OR
  get '/homepage', to: 'users#home', as: 'homepage'

  get '/plants/celebrity', to: 'plants#celebrity', as: 'celebrity'
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  resources :users, :gardens, only: [:new, :index, :create, :show]
  resources :plants, only: [:index, :show]

  resources :users, only: [:show, :index] do
    resources :gardens
  end

end#ender

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
    belongs_to :user
    belongs_to :plant
    validates :address, presence: true
    validates :plant, uniqueness: {scope: :address, message: "error: You already have this plant saved at this address!" }
    accepts_nested_attributes_for :plant, reject_if: proc { |attributes| attributes['name'].blank? }

    
end

app/models/plant.rb
class Plant < ApplicationRecord
    has_many :gardens
    has_many :users, through: :gardens
    validates :name, :description, presence: true
    validates_uniqueness_of :name, :case_sensitive => false
    
    scope :celebrity, -> {joins(:gardens).group(:id).having('COUNT(plant_id)>=1').order('COUNT(user_id) desc')}

    def self.sort_names
        order(:name)
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :gardens
    has_many :plants, through: :gardens
    has_secure_password
    validates :email, uniqueness: true
    validates :name, :email, presence: true

    def self.google_user(auth)
        find_or_create_by(email: auth[:info][:email]) do |u|
            u.name = auth[:info][:name] 
            u.email = auth[:info][:email] 
            u.password = SecureRandom.hex
        end
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController 
    before_action :redirect_if_not_logged_in

    def new
        @garden = Garden.new(user_id: current_user.id)
        @garden.build_plant
    end

    def create
        @garden = Garden.new(garden_params)
        if @garden.save
            redirect_to user_garden_path(@garden.user, @garden)
        else
            render :new
        end
    end

    def show
        @garden = Garden.find(params[:id])
    end


    def index
        if params[:user_id]
            @gardens = Garden.where(user_id: params[:user_id])
        else
            @gardens = Garden.all.where.not(user_id: current_user.id)
        end
    end

    def destroy
        Garden.find(params[:id]).destroy
        redirect_to user_gardens_path(current_user)
    end

    private
    def garden_params
        params.require(:garden).permit(:user_id, :address, :plant_id, plant_attributes: [:name, :description])
    end

end#class ender

app/controllers/plants_controller.rb
class PlantsController < ApplicationController 
    before_action :redirect_if_not_logged_in

    def index
        @plants = Plant.all
    end
    
    def show
        @plant = Plant.find(params[:id])
    end

    def celebrity
        @celebrity = Plant.celebrity
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    #site main page
    def main
    end

    def new
    end

    def create
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id    
            redirect_to homepage_path
        else
            flash[:error] = "Invalid entry, please try again."
            redirect_to login_path
        end
    end
    
    def omniauth
        @user = User.google_user(auth)
        session[:user_id] = @user.id    
        redirect_to homepage_path
    end
    
    def destroy
        session.delete :user_id
        redirect_to root_path
     end


     private

     def auth
        request.env['omniauth.auth']
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    def new
        @user = User.new
    end
    
    #users home page
    def home
        redirect_to login_path if !current_user
    end

    def about
    end

    def create
        @user = User.new(user_params)
        #if youre able to save the user, login and render homepage
        if @user.save
            session[:user_id] = @user.id
            redirect_to homepage_path
        else
            #else render login again
            flash[:alert] = "Invalid entry, please try again."
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)    
    end
end #class ender

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def nested_route?
        !!params[:user_id]
    end

    def redirect_if_not_logged_in
        flash[:error] = "You have to login to view that page!"
        redirect_to login_path if !logged_in?
    end
    
    def display_flash
        flash[:error] if !logged_in?
    end
    
    def display_links
        (link_to "all gardens", gardens_path) + " || " +
        (link_to "all plants", plants_path) + " || " +
        (link_to "add garden", new_user_garden_path(current_user)) + " || " +
        (link_to "my gardens", user_gardens_path(current_user)) +
        content_tag(:br)

    end
end

app/helpers/gardens_helper.rb
module GardensHelper
    #helper to see other users plants aka Plant.all without current users plants
    #to be used in the gardens/new collection
    def other_plants
        plants = current_user.plants
           plants.map do |p|
           @other_plants = Plant.where.not(name: p.name)
       end
       @other_plants ||= Plant.all
    end

    def display_owner(user)
        if user != current_user 
           content_tag(:p, "#{user.name} owns this plant.")
       end 
   end

   def delete_button(garden)
        if garden.user == current_user 
        (button_to "Delete this garden", user_garden_path(current_user, garden), method: :delete)
        end 
   end

    def index_header
        if !!params[:user_id] && current_user.gardens.empty?
            content_tag(:h1, "Hey, #{current_user.name}!") + content_tag(:h3, "Create a garden first, and then you'll see it here!")
        elsif !!params[:user_id] 
            content_tag(:h1, "Hey, #{current_user.name}! Here are your gardens.")
        else
            content_tag(:h1, "All Gardens")
        end
    end

    def last_garden
        recent_g = current_user.gardens.last
        recent_g.created_at
    end

end

app/views/gardens/index.html.erb
<%= index_header %>
<%= display_links %>
<div align="right">
    <h4> Check out our plant-celebrity lineup!</h4>
    <%= link_to "GardenKeeper's Celebrity Showcase", celebrity_path %>
</div>
<%= display_flash %>


<% @gardens.each do |g| %>
    <h2>Address: <%= link_to g.address, garden_path(g) %></h2>

    <%= display_owner(g.user) %>

    <p>Plant name: <%= link_to g.plant.name.capitalize, plant_path(g.plant) %> </p>
    <p>Description: <%= g.plant.description %> </p>
    <br>
<% end %>

app/views/gardens/new.html.erb
<h1> Create a Garden! </h1>
<%= display_flash %>

<% if @garden.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@garden.errors.count, "error") %> prohibited this garden from being saved:</h2>
    <ul>
    <% @garden.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<br><br>

<%= form_for @garden do |f| %>
    <%= f.hidden_field :user_id %>
      <%= f.fields_for :plant do |p| %>
        <p>
          What kind of plant is in your garden? 
        </p>
        <div>
          <%= p.label :name %>
          <%= p.text_field :name %>
        </div>
        <div>
          <%= p.label :description %>
          <%= p.text_area :description %>
        </div>
      <% end %>
<br>
  <p> 
    Or, maybe this kind of plant is already in our system! 
  </p>
<div> 
  <%= f.collection_select :plant_id, other_plants.sort_names, :id, :name, include_blank: 'Select existing plant' %>
<br>
</div>
  <p>Where is your garden located?</p>
<div>
        <%= f.label :address %>
        <%= f.text_field :address %>
</div>
        <%= f.submit "Create Garden" %>
        <% end %>

    

app/views/gardens/show.html.erb
<h1> 
    <%= @garden.address %>'s Garden Spotlight 
</h1>
<%= display_flash %>

<div align="right">
    <h4> Check out our plant-celebrity lineup!</h4>
    <%= link_to "GardenKeeper's Celebrity Showcase", celebrity_path %>
</div>

<div>
    <h5>  This garden holds a <%= link_to @garden.plant.name.singularize, plant_path(@garden.plant) %> plant! </h5>
    <h4> Description: <%= @garden.plant.description %> </h4>
    <%= display_owner(@garden.user) %>
</div>

<br>
    <%= link_to "View all your gardens", user_gardens_path(current_user) %>
<br>
<%= delete_button(@garden) %>

app/views/layouts/_form.html.erb
<%= object_name.label :email %>
<%= object_name.email_field :email %>
<br>
<%= object_name.label :password %>
<%= object_name.password_field :password %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
 <head>
 <meta charset="utf-8" />
 <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
 
   <title>GardenKeeper</title>
   <meta name="viewport" content="width=device-width,initial-scale=1">
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>
   <link rel="stylesheet" href="/stylesheets/test.css" />
 
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>
 
 <body>
 <div class="wrapper">
 
   <%= yield %>
 
   <footer class="branding">
   <small>&copy; 2021 <strong><%= link_to "GardenKeeper", root_path%></strong></small>
   
   <% if logged_in? %>
   <%= link_to "about", about_path %>
    <%= link_to current_user.name + ' ' + 'homepage', homepage_path unless current_user.nil? %>
<%= link_to "logout", logout_url, method: :destroy %>
<% end %>
   </footer>
 </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
   <!--[if lt IE 7]>
     <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
     <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
   <![endif]-->
  
 </body>
</html>

app/views/plants/celebrity.html.erb
<div>
   <h1>GardenKeeper's Celebrity showcase!</h1>
   <h4> On this page you'll see our celebrity plants!
   <br> These are our most popular plants, in order from most to least popular according to how many garden's they're in.
   </h4>
</div>

<%= display_flash %>

<br>
<% @celebrity.each do |plant| %>
   <p> 
      <%= link_to plant.name.capitalize, plant_path(plant) %> can be found in <%= pluralize(plant.users.count, "garden") %>!
   </p>
<% end %>

app/views/plants/index.html.erb
<h1>All GardenKeeper Plants</h1>
<%= display_links %>

<div align="right">
    <h4> Check out our plant-celebrity lineup!</h4>
    <%= link_to "GardenKeeper's Celebrity Showcase", celebrity_path %>
    <hr />
</div>

<%= display_flash %>

<div>
    <% @plants.each do |p| %>
        <h3>Name: <%= link_to p.name.capitalize, plant_path(p) %></h3>
        <h5>Description: <%= p.description %> </h5>
        <p> This plant has <%= pluralize(p.users.count, "user") %></p>
        <hr />
    <% end %>
</div>

app/views/plants/show.html.erb
<div>
   <h1> 
      <%= @plant.name %> Page 
   </h1>
</div>

<%= display_flash %>


<div>
   <h4> 
      Description: <%= @plant.description %>
   </h4>
</div>

<div class="sidebar">
 <% @plant.users.each do |user| %>
    <% unless user == current_user %>
       <p>
         <%= user.name %> owns this plant! 
      </p>
      <br>
   <% end %>
   <% end %>
      <p> 
        <%= link_to "View all plants", plants_path %>
      </p>
</div>

app/views/users/about.html.erb
<h1>About GardenKeeper</h1>
<p>This site lets gardeners and regular plant-lovers keep track of their plants and however many gardens they tend to.</p>


Your most recent garden was created at: <%= last_garden %>

app/views/users/home.html.erb
<h1>  Welcome to your GardenKeeper homepage, <%= current_user.name.capitalize %>! </h1>
<br><br>

<% if current_user.gardens.empty? %>
<p> Please create a garden to get started. </p>
<%= link_to "create garden", new_user_garden_path(current_user) %>

<% else %>
<%= link_to "view my gardens", user_gardens_path(current_user) %>
|| <%= link_to "add new garden", new_user_garden_path(current_user) %>
<% end %> 
|| <%= link_to "view all gardens", gardens_path %>
|| <%= link_to "view all plants", plants_path %>
<br>

app/views/users/new.html.erb
<br>
<h2> Create GardenKeeper Account</h2>
<br>
<%= flash[:alert] %>

<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= render partial: '/layouts/form', locals: {object_name: f} %>
    <br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<br>
    <%= f.submit "Create Account" %>
    <% end %>